version: '3'

services:
  kbe:
    container_name: yiwu
    build: .
    ports:
      - "20013:20013"
      - "20015:20015"
      - "20016:20016"
      - "40003:40000"

    stdin_open: true
    tty: true

    volumes:
      - ../Engine/:/kbe/kbengine/
      - ./kbengine/:/kbe/source/

    command: /bin/bash -c "/kbe/source/assets/start_server.sh && tail -f /dev/null"
    # command: "/bin/bash /kbe/source/assets/start_server.sh tail -f  /dev/null"